first_name = input('Enter Your Name : \n')
age = int(input('Enter Your Age : \n'))
print(f'Hello beautiful {first_name}, your age is {age}!')
print(f"Your age modulo 4 is: {age % 4}")
print(f'{22 / 7:.2f}')
print(8 - 2 + 3 * 2 ** 2 / 2)
print(8 -2 + (3 * 2) ** 2 / 2)
